In [1]:
import tensorflow as tf
import numpy as np
import os
import time

In [2]:
path_to_file = tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')

In [3]:
# 读取并为 py2 compat 解码
text = open(path_to_file, 'rb').read().decode(encoding='utf-8')

# 文本长度是指文本中的字符个数
print ('Length of text: {} characters'.format(len(text)))

Length of text: 1115394 characters


In [4]:
# 文本中的非重复字符
vocab = sorted(set(text))
print ('{} unique characters'.format(len(vocab)))

65 unique characters


In [5]:
# 创建从非重复字符到索引的映射
char2idx = {u:i for i, u in enumerate(vocab)}
idx2char = np.array(vocab)

text_as_int = np.array([char2idx[c] for c in text])

In [10]:
# 设定每个输入句子长度的最大值
seq_length = 100
examples_per_epoch = len(text)//seq_length

# 创建训练样本 / 目标
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

In [11]:
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

In [19]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

In [21]:
# 批大小
BATCH_SIZE = 64

# 设定缓冲区大小，以重新排列数据集
# （TF 数据被设计为可以处理可能是无限的序列，
# 所以它不会试图在内存中重新排列整个序列。相反，
# 它维持一个缓冲区，在缓冲区重新排列元素。） 
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

dataset

<BatchDataset shapes: ((64, 100), (64, 100)), types: (tf.int64, tf.int64)>

In [22]:
# 词集的长度
vocab_size = len(vocab)

# 嵌入的维度
embedding_dim = 256

# RNN 的单元数量
rnn_units = 1024

In [23]:
# 由于后面的GRU层设定了stateful=True, 所以必须事先指定batch_size，
# 对于Sequential产生的模型，使用参数batch_input_shape=[batch_size, None]来指定
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, None]
                             ),
    tf.keras.layers.GRU(rnn_units,
                        return_sequences=True,
                        stateful=True,
                        recurrent_initializer='glorot_uniform'),
    tf.keras.layers.Dense(vocab_size)
  ])
  return model

In [24]:
model = build_model(
  vocab_size = len(vocab),
  embedding_dim=embedding_dim,
  rnn_units=rnn_units,
  batch_size=BATCH_SIZE)

In [25]:
a = next(iter(dataset.take(1)))

In [26]:
model.layers[1](model.layers[0](a[0])).shape

TensorShape([64, 100, 1024])

In [30]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)
  print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

(64, 100, 65) # (batch_size, sequence_length, vocab_size)


In [32]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [50]:
target_example_batch[0,]

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([56, 43,  6,  0, 35, 46, 47, 41, 46,  1, 43, 39, 57, 47, 50, 63,  1,
       43, 52, 42, 59, 56, 43, 57,  1, 52, 53, 58,  1, 39, 56, 58, 47, 41,
       50, 43,  0, 32, 63, 47, 52, 45,  1, 46, 47, 51,  1, 58, 53,  1, 39,
       59, 45, 46, 58, 11,  1, 57, 53,  1, 54, 59, 58, 58, 47, 52, 45,  1,
       46, 47, 51,  1, 58, 53,  1, 56, 39, 45, 43,  6,  0, 37, 53, 59,  1,
       57, 46, 53, 59, 50, 42,  1, 46, 39, 60, 43,  1, 58, 39,  5])>

In [34]:
def loss(labels, logits):
  return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

example_batch_loss  = loss(target_example_batch, example_batch_predictions)
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)")
print("scalar_loss:      ", example_batch_loss.numpy().mean())

Prediction shape:  (64, 100, 65)  # (batch_size, sequence_length, vocab_size)
scalar_loss:       4.1750684


In [52]:
example_batch_loss

<tf.Tensor: shape=(64, 100), dtype=float32, numpy=
array([[4.1648755, 4.1828156, 4.1853986, ..., 4.1511283, 4.179807 ,
        4.171203 ],
       [4.1594815, 4.178158 , 4.188442 , ..., 4.2013397, 4.1797824,
        4.1877913],
       [4.185407 , 4.187535 , 4.1571746, ..., 4.1921277, 4.174254 ,
        4.1878705],
       ...,
       [4.1864567, 4.1900954, 4.1807075, ..., 4.187605 , 4.1950984,
        4.168958 ],
       [4.175723 , 4.1629195, 4.1787505, ..., 4.1797543, 4.1732755,
        4.1803513],
       [4.1598053, 4.1568694, 4.1778584, ..., 4.192817 , 4.172582 ,
        4.181738 ]], dtype=float32)>

In [35]:
model.compile(optimizer='adam', loss=loss)

In [36]:
# 检查点保存至的目录
checkpoint_dir = './training_checkpoints'

# 检查点的文件名
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

In [37]:
EPOCHS=6

In [38]:
history = model.fit(dataset, epochs=EPOCHS, callbacks=[checkpoint_callback], steps_per_epoch=50)

Train for 50 steps
Epoch 1/6
50/50 [==============================] - 66s 1s/step - loss: 3.3690
Epoch 2/6
37/50 [=====================>........] - ETA: 19s - loss: 2.5389

KeyboardInterrupt: 

In [39]:
tf.train.latest_checkpoint('./training_checkpoints/')

'./training_checkpoints/ckpt_2'

In [53]:
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size=1)

model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

model.build(tf.TensorShape([1, None]))

In [54]:
start_string=u"ROMEO: "

In [55]:
num_generate = 1000

In [56]:
input_eval = [char2idx[s] for s in start_string]
input_eval = tf.expand_dims(input_eval, 0)

In [58]:
text_generated = []
temperature = 1.0
model.reset_states()

In [60]:
model(input_eval).shape

TensorShape([1, 7, 65])

In [61]:
predictions = model(input_eval)
predictions = tf.squeeze(predictions, 0)
predictions = predictions / temperature
predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

In [62]:
input_eval = tf.expand_dims([predicted_id], 0)

In [64]:
input_eval

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[20]], dtype=int32)>

In [48]:
predicted_id

20

In [173]:
input_eval = tf.expand_dims([predicted_id], 0)

In [174]:
input_eval

<tf.Tensor: id=87184, shape=(1, 1), dtype=int32, numpy=array([[39]], dtype=int32)>

In [65]:
text_generated.append(idx2char[predicted_id])

In [66]:
text_generated

['H']

In [69]:
model(input_eval).shape

TensorShape([1, 1, 65])

In [178]:
predictions = model(input_eval)

In [179]:
predictions = tf.squeeze(predictions, 0)

In [180]:
predictions = predictions / temperature

In [181]:
predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

In [183]:
input_eval = tf.expand_dims([predicted_id], 0)

In [184]:
text_generated.append(idx2char[predicted_id])

In [185]:
text_generated

['a', 'd']